#############################################################################
# Makefile for building: objviewer
# Generated by qmake (3.0) (Qt 5.0.2) on: Thu Jun 20 12:39:49 2013
# Project:  Q3DViewer.pro
# Template: app
# Command: /usr/lib/qt/bin/qmake -o Makefile Q3DViewer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -DDEBUG -fopenmp -Isrc/include -g `Magick++-config --cppflags` `pkg-config --cflags opencv` -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/qt/mkspecs/linux-g++-64 -I. -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -Ibuild/moc -Ibuild/ui
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 `Magick++-config --libs` `pkg-config --libs opencv` -fopenmp -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = Qt.cpp \
		mainwindow.cpp \
		src/color.cc \
		src/lib/debugutils.cc \
		src/lib/imagereader.cc \
		src/lib/kdtree.cc \
		src/lib/objreader.cc \
		src/lib/Timer.cc \
		src/lib/utils.cc \
		src/renderable/face.cc \
		src/renderable/mesh.cc \
		src/renderable/plane.cc \
		src/renderable/sphere.cc \
		src/space.cc \
		src/surface.cc \
		src/texture.cc \
		src/view.cc \
		src/mesh_simplifier.cc \
		src/cvrender.cc build/moc/moc_mainwindow.cpp
OBJECTS       = build/obj/Qt.o \
		build/obj/mainwindow.o \
		build/obj/color.o \
		build/obj/debugutils.o \
		build/obj/imagereader.o \
		build/obj/kdtree.o \
		build/obj/objreader.o \
		build/obj/Timer.o \
		build/obj/utils.o \
		build/obj/face.o \
		build/obj/mesh.o \
		build/obj/plane.o \
		build/obj/sphere.o \
		build/obj/space.o \
		build/obj/surface.o \
		build/obj/texture.o \
		build/obj/view.o \
		build/obj/mesh_simplifier.o \
		build/obj/cvrender.o \
		build/obj/moc_mainwindow.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/shell-unix.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_v8.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/unix/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/wayland-scanner.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		Q3DViewer.pro \
		Q3DViewer.pro
QMAKE_TARGET  = objviewer
DESTDIR       = 
TARGET        = objviewer


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui/ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Q3DViewer.pro /usr/lib/qt/mkspecs/linux-g++-64/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/shell-unix.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_v8.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/unix/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/wayland-scanner.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		Q3DViewer.pro \
		/lib/libQt5Widgets.prl \
		/lib/libQt5Gui.prl \
		/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Q3DViewer.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/shell-unix.conf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_clucene.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_v8.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/unix/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/wayland-scanner.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
Q3DViewer.pro:
/lib/libQt5Widgets.prl:
/lib/libQt5Gui.prl:
/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Q3DViewer.pro

qmake_all: FORCE

dist: 
	@test -d build/obj/objviewer1.0.0 || mkdir -p build/obj/objviewer1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/obj/objviewer1.0.0/ && $(COPY_FILE) --parents mainwindow.h src/include/geometry/aabb.hh src/include/geometry/geometry.hh src/include/geometry/infplane.hh src/include/geometry/ray.hh src/include/geometry/sphere.hh src/include/material/surface.hh src/include/material/texture.hh src/include/renderable/face.hh src/include/renderable/mesh.hh src/include/renderable/plane.hh src/include/renderable/renderable.hh src/include/renderable/sphere.hh src/include/color.hh src/include/common.hh src/include/matrix.hh src/include/mesh_simplifier.hh src/include/space.hh src/include/view.hh src/include/viewer.hh build/obj/objviewer1.0.0/ && $(COPY_FILE) --parents Qt.cpp mainwindow.cpp src/color.cc src/lib/debugutils.cc src/lib/imagereader.cc src/lib/kdtree.cc src/lib/objreader.cc src/lib/Timer.cc src/lib/utils.cc src/renderable/face.cc src/renderable/mesh.cc src/renderable/plane.cc src/renderable/sphere.cc src/space.cc src/surface.cc src/texture.cc src/view.cc src/mesh_simplifier.cc src/cvrender.cc build/obj/objviewer1.0.0/ && $(COPY_FILE) --parents mainwindow.ui build/obj/objviewer1.0.0/ && (cd `dirname build/obj/objviewer1.0.0` && $(TAR) objviewer1.0.0.tar objviewer1.0.0 && $(COMPRESS) objviewer1.0.0.tar) && $(MOVE) `dirname build/obj/objviewer1.0.0`/objviewer1.0.0.tar.gz . && $(DEL_FILE) -r build/obj/objviewer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_moc_header_make_all: build/moc/moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_mainwindow.cpp
build/moc/moc_mainwindow.cpp: /usr/include/qt/QtWidgets/QMainWindow \
		/usr/include/qt/QtWidgets/qmainwindow.h \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtWidgets/qtabwidget.h \
		/usr/include/qt/QtGui/qicon.h \
		/usr/include/qt/QtWidgets/QAction \
		/usr/include/qt/QtWidgets/qaction.h \
		/usr/include/qt/QtWidgets/qactiongroup.h \
		/usr/include/qt/QtWidgets/QPushButton \
		/usr/include/qt/QtWidgets/qpushbutton.h \
		/usr/include/qt/QtWidgets/qabstractbutton.h \
		/usr/include/qt/QtWidgets/QGraphicsView \
		/usr/include/qt/QtWidgets/qgraphicsview.h \
		/usr/include/qt/QtGui/qpainter.h \
		/usr/include/qt/QtGui/qtextoption.h \
		/usr/include/qt/QtGui/qpen.h \
		/usr/include/qt/QtWidgets/qscrollarea.h \
		/usr/include/qt/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt/QtWidgets/qframe.h \
		/usr/include/qt/QtWidgets/qgraphicsscene.h \
		/usr/include/qt/QtGui/QPixmap \
		/usr/include/qt/QtCore/QPoint \
		/usr/include/qt/QtGui/QColor \
		/usr/include/qt/QtWidgets/QCheckBox \
		/usr/include/qt/QtWidgets/qcheckbox.h \
		/usr/include/qt/QtCore/QTimer \
		/usr/include/qt/QtCore/qtimer.h \
		/usr/include/qt/QtCore/qbasictimer.h \
		/usr/include/qt/QtWidgets/QLineEdit \
		/usr/include/qt/QtWidgets/qlineedit.h \
		/usr/include/qt/QtGui/qtextcursor.h \
		/usr/include/qt/QtGui/qtextformat.h \
		/usr/include/qt/QtWidgets/QMessageBox \
		/usr/include/qt/QtWidgets/qmessagebox.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtCore/QFile \
		/usr/include/qt/QtWidgets/QDial \
		/usr/include/qt/QtWidgets/qdial.h \
		/usr/include/qt/QtWidgets/qabstractslider.h \
		/usr/include/qt/QtWidgets/QFileDialog \
		/usr/include/qt/QtWidgets/qfiledialog.h \
		/usr/include/qt/QtCore/qdir.h \
		/usr/include/qt/QtCore/qfileinfo.h \
		/usr/include/qt/QtCore/QTextStream \
		/usr/include/qt/QtCore/QThread \
		/usr/include/qt/QtCore/qthread.h \
		/usr/include/qt/QtWidgets/QComboBox \
		/usr/include/qt/QtWidgets/qcombobox.h \
		/usr/include/qt/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt/QtWidgets/qstyleoption.h \
		/usr/include/qt/QtWidgets/qabstractspinbox.h \
		/usr/include/qt/QtGui/qvalidator.h \
		/usr/include/qt/QtWidgets/qslider.h \
		/usr/include/qt/QtWidgets/qstyle.h \
		/usr/include/qt/QtWidgets/qtabbar.h \
		/usr/include/qt/QtWidgets/qrubberband.h \
		/usr/include/qt/QtCore/qabstractitemmodel.h \
		/usr/include/qt/QtWidgets/QSlider \
		/usr/include/qt/QtWidgets/QPlainTextEdit \
		/usr/include/qt/QtWidgets/qplaintextedit.h \
		/usr/include/qt/QtWidgets/qtextedit.h \
		/usr/include/qt/QtGui/qtextdocument.h \
		/usr/include/qt/QtGui/qabstracttextdocumentlayout.h \
		/usr/include/qt/QtGui/qtextlayout.h \
		/usr/include/qt/QtGui/qglyphrun.h \
		/usr/include/qt/QtGui/qrawfont.h \
		/usr/include/qt/QtGui/qfontdatabase.h \
		mainwindow.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o build/moc/moc_mainwindow.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui/ui_mainwindow.h
build/ui/ui_mainwindow.h: mainwindow.ui
	/usr/lib/qt/bin/uic mainwindow.ui -o build/ui/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/obj/Qt.o: Qt.cpp mainwindow.h \
		/usr/include/qt/QtWidgets/QMainWindow \
		/usr/include/qt/QtWidgets/qmainwindow.h \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtWidgets/qtabwidget.h \
		/usr/include/qt/QtGui/qicon.h \
		/usr/include/qt/QtWidgets/QAction \
		/usr/include/qt/QtWidgets/qaction.h \
		/usr/include/qt/QtWidgets/qactiongroup.h \
		/usr/include/qt/QtWidgets/QPushButton \
		/usr/include/qt/QtWidgets/qpushbutton.h \
		/usr/include/qt/QtWidgets/qabstractbutton.h \
		/usr/include/qt/QtWidgets/QGraphicsView \
		/usr/include/qt/QtWidgets/qgraphicsview.h \
		/usr/include/qt/QtGui/qpainter.h \
		/usr/include/qt/QtGui/qtextoption.h \
		/usr/include/qt/QtGui/qpen.h \
		/usr/include/qt/QtWidgets/qscrollarea.h \
		/usr/include/qt/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt/QtWidgets/qframe.h \
		/usr/include/qt/QtWidgets/qgraphicsscene.h \
		/usr/include/qt/QtGui/QPixmap \
		/usr/include/qt/QtCore/QPoint \
		/usr/include/qt/QtGui/QColor \
		/usr/include/qt/QtWidgets/QCheckBox \
		/usr/include/qt/QtWidgets/qcheckbox.h \
		/usr/include/qt/QtCore/QTimer \
		/usr/include/qt/QtCore/qtimer.h \
		/usr/include/qt/QtCore/qbasictimer.h \
		/usr/include/qt/QtWidgets/QLineEdit \
		/usr/include/qt/QtWidgets/qlineedit.h \
		/usr/include/qt/QtGui/qtextcursor.h \
		/usr/include/qt/QtGui/qtextformat.h \
		/usr/include/qt/QtWidgets/QMessageBox \
		/usr/include/qt/QtWidgets/qmessagebox.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtCore/QFile \
		/usr/include/qt/QtWidgets/QDial \
		/usr/include/qt/QtWidgets/qdial.h \
		/usr/include/qt/QtWidgets/qabstractslider.h \
		/usr/include/qt/QtWidgets/QFileDialog \
		/usr/include/qt/QtWidgets/qfiledialog.h \
		/usr/include/qt/QtCore/qdir.h \
		/usr/include/qt/QtCore/qfileinfo.h \
		/usr/include/qt/QtCore/QTextStream \
		/usr/include/qt/QtCore/QThread \
		/usr/include/qt/QtCore/qthread.h \
		/usr/include/qt/QtWidgets/QComboBox \
		/usr/include/qt/QtWidgets/qcombobox.h \
		/usr/include/qt/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt/QtWidgets/qstyleoption.h \
		/usr/include/qt/QtWidgets/qabstractspinbox.h \
		/usr/include/qt/QtGui/qvalidator.h \
		/usr/include/qt/QtWidgets/qslider.h \
		/usr/include/qt/QtWidgets/qstyle.h \
		/usr/include/qt/QtWidgets/qtabbar.h \
		/usr/include/qt/QtWidgets/qrubberband.h \
		/usr/include/qt/QtCore/qabstractitemmodel.h \
		/usr/include/qt/QtWidgets/QSlider \
		/usr/include/qt/QtWidgets/QPlainTextEdit \
		/usr/include/qt/QtWidgets/qplaintextedit.h \
		/usr/include/qt/QtWidgets/qtextedit.h \
		/usr/include/qt/QtGui/qtextdocument.h \
		/usr/include/qt/QtGui/qabstracttextdocumentlayout.h \
		/usr/include/qt/QtGui/qtextlayout.h \
		/usr/include/qt/QtGui/qglyphrun.h \
		/usr/include/qt/QtGui/qrawfont.h \
		/usr/include/qt/QtGui/qfontdatabase.h \
		/usr/include/qt/QtWidgets/QApplication \
		/usr/include/qt/QtWidgets/qapplication.h \
		/usr/include/qt/QtCore/qcoreapplication.h \
		/usr/include/qt/QtCore/qeventloop.h \
		/usr/include/qt/QtWidgets/qdesktopwidget.h \
		/usr/include/qt/QtGui/qguiapplication.h \
		/usr/include/qt/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Qt.o Qt.cpp

build/obj/mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/include/qt/QtWidgets/QMainWindow \
		/usr/include/qt/QtWidgets/qmainwindow.h \
		/usr/include/qt/QtWidgets/qwidget.h \
		/usr/include/qt/QtGui/qwindowdefs.h \
		/usr/include/qt/QtCore/qglobal.h \
		/usr/include/qt/QtCore/qconfig.h \
		/usr/include/qt/QtCore/qfeatures.h \
		/usr/include/qt/QtCore/qsystemdetection.h \
		/usr/include/qt/QtCore/qcompilerdetection.h \
		/usr/include/qt/QtCore/qprocessordetection.h \
		/usr/include/qt/QtCore/qlogging.h \
		/usr/include/qt/QtCore/qflags.h \
		/usr/include/qt/QtCore/qtypeinfo.h \
		/usr/include/qt/QtCore/qtypetraits.h \
		/usr/include/qt/QtCore/qsysinfo.h \
		/usr/include/qt/QtCore/qobjectdefs.h \
		/usr/include/qt/QtCore/qnamespace.h \
		/usr/include/qt/QtCore/qobjectdefs_impl.h \
		/usr/include/qt/QtGui/qwindowdefs_win.h \
		/usr/include/qt/QtCore/qobject.h \
		/usr/include/qt/QtCore/qstring.h \
		/usr/include/qt/QtCore/qchar.h \
		/usr/include/qt/QtCore/qbytearray.h \
		/usr/include/qt/QtCore/qrefcount.h \
		/usr/include/qt/QtCore/qatomic.h \
		/usr/include/qt/QtCore/qbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_bootstrap.h \
		/usr/include/qt/QtCore/qgenericatomic.h \
		/usr/include/qt/QtCore/qatomic_msvc.h \
		/usr/include/qt/QtCore/qatomic_integrity.h \
		/usr/include/qt/QtCore/qoldbasicatomic.h \
		/usr/include/qt/QtCore/qatomic_vxworks.h \
		/usr/include/qt/QtCore/qatomic_power.h \
		/usr/include/qt/QtCore/qatomic_alpha.h \
		/usr/include/qt/QtCore/qatomic_armv7.h \
		/usr/include/qt/QtCore/qatomic_armv6.h \
		/usr/include/qt/QtCore/qatomic_armv5.h \
		/usr/include/qt/QtCore/qatomic_bfin.h \
		/usr/include/qt/QtCore/qatomic_ia64.h \
		/usr/include/qt/QtCore/qatomic_mips.h \
		/usr/include/qt/QtCore/qatomic_s390.h \
		/usr/include/qt/QtCore/qatomic_sh4a.h \
		/usr/include/qt/QtCore/qatomic_sparc.h \
		/usr/include/qt/QtCore/qatomic_x86.h \
		/usr/include/qt/QtCore/qatomic_cxx11.h \
		/usr/include/qt/QtCore/qatomic_gcc.h \
		/usr/include/qt/QtCore/qatomic_unix.h \
		/usr/include/qt/QtCore/qarraydata.h \
		/usr/include/qt/QtCore/qstringbuilder.h \
		/usr/include/qt/QtCore/qlist.h \
		/usr/include/qt/QtCore/qalgorithms.h \
		/usr/include/qt/QtCore/qiterator.h \
		/usr/include/qt/QtCore/qcoreevent.h \
		/usr/include/qt/QtCore/qscopedpointer.h \
		/usr/include/qt/QtCore/qmetatype.h \
		/usr/include/qt/QtCore/qvarlengtharray.h \
		/usr/include/qt/QtCore/qcontainerfwd.h \
		/usr/include/qt/QtCore/qisenum.h \
		/usr/include/qt/QtCore/qobject_impl.h \
		/usr/include/qt/QtCore/qmargins.h \
		/usr/include/qt/QtGui/qpaintdevice.h \
		/usr/include/qt/QtCore/qrect.h \
		/usr/include/qt/QtCore/qsize.h \
		/usr/include/qt/QtCore/qpoint.h \
		/usr/include/qt/QtGui/qpalette.h \
		/usr/include/qt/QtGui/qcolor.h \
		/usr/include/qt/QtGui/qrgb.h \
		/usr/include/qt/QtCore/qstringlist.h \
		/usr/include/qt/QtCore/qdatastream.h \
		/usr/include/qt/QtCore/qiodevice.h \
		/usr/include/qt/QtCore/qpair.h \
		/usr/include/qt/QtCore/qregexp.h \
		/usr/include/qt/QtCore/qstringmatcher.h \
		/usr/include/qt/QtGui/qbrush.h \
		/usr/include/qt/QtCore/qvector.h \
		/usr/include/qt/QtGui/qmatrix.h \
		/usr/include/qt/QtGui/qpolygon.h \
		/usr/include/qt/QtGui/qregion.h \
		/usr/include/qt/QtCore/qline.h \
		/usr/include/qt/QtGui/qtransform.h \
		/usr/include/qt/QtGui/qpainterpath.h \
		/usr/include/qt/QtGui/qimage.h \
		/usr/include/qt/QtGui/qpixmap.h \
		/usr/include/qt/QtCore/qsharedpointer.h \
		/usr/include/qt/QtCore/qshareddata.h \
		/usr/include/qt/QtCore/qsharedpointer_impl.h \
		/usr/include/qt/QtCore/qhash.h \
		/usr/include/qt/QtGui/qfont.h \
		/usr/include/qt/QtGui/qfontmetrics.h \
		/usr/include/qt/QtGui/qfontinfo.h \
		/usr/include/qt/QtWidgets/qsizepolicy.h \
		/usr/include/qt/QtGui/qcursor.h \
		/usr/include/qt/QtGui/qkeysequence.h \
		/usr/include/qt/QtGui/qevent.h \
		/usr/include/qt/QtCore/qvariant.h \
		/usr/include/qt/QtCore/qmap.h \
		/usr/include/qt/QtCore/qdebug.h \
		/usr/include/qt/QtCore/qtextstream.h \
		/usr/include/qt/QtCore/qlocale.h \
		/usr/include/qt/QtCore/qset.h \
		/usr/include/qt/QtCore/qcontiguouscache.h \
		/usr/include/qt/QtCore/qurl.h \
		/usr/include/qt/QtCore/qurlquery.h \
		/usr/include/qt/QtCore/qfile.h \
		/usr/include/qt/QtCore/qfiledevice.h \
		/usr/include/qt/QtGui/qvector2d.h \
		/usr/include/qt/QtGui/qtouchdevice.h \
		/usr/include/qt/QtWidgets/qtabwidget.h \
		/usr/include/qt/QtGui/qicon.h \
		/usr/include/qt/QtWidgets/QAction \
		/usr/include/qt/QtWidgets/qaction.h \
		/usr/include/qt/QtWidgets/qactiongroup.h \
		/usr/include/qt/QtWidgets/QPushButton \
		/usr/include/qt/QtWidgets/qpushbutton.h \
		/usr/include/qt/QtWidgets/qabstractbutton.h \
		/usr/include/qt/QtWidgets/QGraphicsView \
		/usr/include/qt/QtWidgets/qgraphicsview.h \
		/usr/include/qt/QtGui/qpainter.h \
		/usr/include/qt/QtGui/qtextoption.h \
		/usr/include/qt/QtGui/qpen.h \
		/usr/include/qt/QtWidgets/qscrollarea.h \
		/usr/include/qt/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt/QtWidgets/qframe.h \
		/usr/include/qt/QtWidgets/qgraphicsscene.h \
		/usr/include/qt/QtGui/QPixmap \
		/usr/include/qt/QtCore/QPoint \
		/usr/include/qt/QtGui/QColor \
		/usr/include/qt/QtWidgets/QCheckBox \
		/usr/include/qt/QtWidgets/qcheckbox.h \
		/usr/include/qt/QtCore/QTimer \
		/usr/include/qt/QtCore/qtimer.h \
		/usr/include/qt/QtCore/qbasictimer.h \
		/usr/include/qt/QtWidgets/QLineEdit \
		/usr/include/qt/QtWidgets/qlineedit.h \
		/usr/include/qt/QtGui/qtextcursor.h \
		/usr/include/qt/QtGui/qtextformat.h \
		/usr/include/qt/QtWidgets/QMessageBox \
		/usr/include/qt/QtWidgets/qmessagebox.h \
		/usr/include/qt/QtWidgets/qdialog.h \
		/usr/include/qt/QtCore/QFile \
		/usr/include/qt/QtWidgets/QDial \
		/usr/include/qt/QtWidgets/qdial.h \
		/usr/include/qt/QtWidgets/qabstractslider.h \
		/usr/include/qt/QtWidgets/QFileDialog \
		/usr/include/qt/QtWidgets/qfiledialog.h \
		/usr/include/qt/QtCore/qdir.h \
		/usr/include/qt/QtCore/qfileinfo.h \
		/usr/include/qt/QtCore/QTextStream \
		/usr/include/qt/QtCore/QThread \
		/usr/include/qt/QtCore/qthread.h \
		/usr/include/qt/QtWidgets/QComboBox \
		/usr/include/qt/QtWidgets/qcombobox.h \
		/usr/include/qt/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt/QtWidgets/qstyleoption.h \
		/usr/include/qt/QtWidgets/qabstractspinbox.h \
		/usr/include/qt/QtGui/qvalidator.h \
		/usr/include/qt/QtWidgets/qslider.h \
		/usr/include/qt/QtWidgets/qstyle.h \
		/usr/include/qt/QtWidgets/qtabbar.h \
		/usr/include/qt/QtWidgets/qrubberband.h \
		/usr/include/qt/QtCore/qabstractitemmodel.h \
		/usr/include/qt/QtWidgets/QSlider \
		/usr/include/qt/QtWidgets/QPlainTextEdit \
		/usr/include/qt/QtWidgets/qplaintextedit.h \
		/usr/include/qt/QtWidgets/qtextedit.h \
		/usr/include/qt/QtGui/qtextdocument.h \
		/usr/include/qt/QtGui/qabstracttextdocumentlayout.h \
		/usr/include/qt/QtGui/qtextlayout.h \
		/usr/include/qt/QtGui/qglyphrun.h \
		/usr/include/qt/QtGui/qrawfont.h \
		/usr/include/qt/QtGui/qfontdatabase.h \
		build/ui/ui_mainwindow.h \
		/usr/include/qt/QtCore/QVariant \
		/usr/include/qt/QtWidgets/QApplication \
		/usr/include/qt/QtWidgets/qapplication.h \
		/usr/include/qt/QtCore/qcoreapplication.h \
		/usr/include/qt/QtCore/qeventloop.h \
		/usr/include/qt/QtWidgets/qdesktopwidget.h \
		/usr/include/qt/QtGui/qguiapplication.h \
		/usr/include/qt/QtGui/qinputmethod.h \
		/usr/include/qt/QtWidgets/QButtonGroup \
		/usr/include/qt/QtWidgets/qbuttongroup.h \
		/usr/include/qt/QtWidgets/QFrame \
		/usr/include/qt/QtWidgets/QHeaderView \
		/usr/include/qt/QtWidgets/qheaderview.h \
		/usr/include/qt/QtWidgets/qabstractitemview.h \
		/usr/include/qt/QtCore/qitemselectionmodel.h \
		/usr/include/qt/QtWidgets/QLabel \
		/usr/include/qt/QtWidgets/qlabel.h \
		/usr/include/qt/QtWidgets/QMenuBar \
		/usr/include/qt/QtWidgets/qmenubar.h \
		/usr/include/qt/QtWidgets/qmenu.h \
		/usr/include/qt/QtWidgets/QStatusBar \
		/usr/include/qt/QtWidgets/qstatusbar.h \
		/usr/include/qt/QtWidgets/QToolBar \
		/usr/include/qt/QtWidgets/qtoolbar.h \
		/usr/include/qt/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/mainwindow.o mainwindow.cpp

build/obj/color.o: src/color.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/color.o src/color.cc

build/obj/debugutils.o: src/lib/debugutils.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/debugutils.o src/lib/debugutils.cc

build/obj/imagereader.o: src/lib/imagereader.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/imagereader.o src/lib/imagereader.cc

build/obj/kdtree.o: src/lib/kdtree.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/kdtree.o src/lib/kdtree.cc

build/obj/objreader.o: src/lib/objreader.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/objreader.o src/lib/objreader.cc

build/obj/Timer.o: src/lib/Timer.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Timer.o src/lib/Timer.cc

build/obj/utils.o: src/lib/utils.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/utils.o src/lib/utils.cc

build/obj/face.o: src/renderable/face.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/face.o src/renderable/face.cc

build/obj/mesh.o: src/renderable/mesh.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/mesh.o src/renderable/mesh.cc

build/obj/plane.o: src/renderable/plane.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/plane.o src/renderable/plane.cc

build/obj/sphere.o: src/renderable/sphere.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/sphere.o src/renderable/sphere.cc

build/obj/space.o: src/space.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/space.o src/space.cc

build/obj/surface.o: src/surface.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/surface.o src/surface.cc

build/obj/texture.o: src/texture.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/texture.o src/texture.cc

build/obj/view.o: src/view.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/view.o src/view.cc

build/obj/mesh_simplifier.o: src/mesh_simplifier.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/mesh_simplifier.o src/mesh_simplifier.cc

build/obj/cvrender.o: src/cvrender.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/cvrender.o src/cvrender.cc

build/obj/moc_mainwindow.o: build/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_mainwindow.o build/moc/moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

